# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FPGAs in Space
email: shane.fleming06@imperial.ac.uk
description: > # this means to ignore newlines until "baseurl:"
            Blog detailing the experiments onboard the ESA OPS-SAT mission developed by
            the Circuits and Systems Group at Imperial College London.
baseurl: "/ops-sat" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: cas_OPS-SAT
github_username:  sf306

# Build settings
markdown: kramdown
