# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FPGAs in Space
email: shane.fleming06@imperial.ac.uk
description: > # this means to ignore newlines until "baseurl:"
        A blog documenting the progress of the European Space Agency OPS-SAT experiments
        being developed at the Circuits and Systems Group Imperial College London, where
        the viability of Commercial Off The Shelf (COTS) Field Programmable Gate Arrays (FPGA)
        in space is being explored.
baseurl: "/ops-sat" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site
twitter_username: cas_OPS-SAT
github_username:  sf306

# Build settings
markdown: kramdown
